# Generated by Django 4.0.7 on 2024-08-17 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_alter_driver_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='userid',
            new_name='user',
        ),
    ]
